@echo off
echo Starting Mistral Assistant...
cd /d "%~dp0"
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing/updating dependencies...
pip install -r requirements.txt
echo Starting server...
python api\app.py
pause
